# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Check
          command: ls -la

      - run:
          name: install-serverless
          command: npm install -g serverless

      - run:
          name: Check
          command: ls -la



#   deploy-dev:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:10.9

#     working_directory: ~/repo

#     steps:

#       - attach_workspace:
#           at: ~/repo

#       - run:
#           name: install aws cli
#           command: sudo apt-get -y -qq install awscli
#       - run:
#           name: Check
#           command: ls -la
#       - run:
#           name: deploy S3
#           command: aws s3 sync dist s3://ener-auction-develop/

#   deploy-stg:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:10.9

#     working_directory: ~/repo

#     steps:

#       - attach_workspace:
#           at: ~/repo

#       - run:
#           name: install aws cli
#           command: sudo apt-get -y -qq install awscli
#       - run:
#           name: Check
#           command: ls -la
#       - run:
#           name: remove unnecessary contents     # LandingPageのindex.html,faviconなど上書きしないために削除
#           command: rm dist/index.html dist/README.md
#       - run:
#           name: deploy S3
#           command: aws s3 sync dist s3://ener-auction-staging/

#   deploy-release:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:10.9

#     working_directory: ~/repo

#     steps:

#       - attach_workspace:
#           at: ~/repo

#       - run:
#           name: install aws cli
#           command: sudo apt-get -y -qq install awscli
#       - run:
#           name: Check
#           command: ls -la
#       - run:
#           name: remove unnecessary contents     # LandingPageのindex.html,faviconなど上書きしないために削除
#           command: rm dist/index.html dist/README.md
#       - run:
#           name: deploy S3
#           command: aws s3 sync dist s3://auctions.enerbank.co.jp/ --region ap-northeast-1

# workflows:
#   version: 2
#   build_and_deploy: # workflow名
#     jobs:
#       - build
#       - deploy-dev:
#           requires: # buildが成功したら実行する
#             - build
#           filters: # developブランチの場合のデプロイす
#             branches:
#               only: develop

#       - deploy-stg:
#           requires: # buildが成功したら実行する
#             - build
#           filters: # stgブランチの場合のデプロイ
#             branches:
#               only: 
#                 - staging

#       - deploy-release:
#           requires: # buildが成功したら実行する
#             - build
#           filters: # stgブランチの場合のデプロイ
#             branches:
#               only:
#                 - release